name: Deploy app to Azure app service

on:
  push:
    branches:
      - main
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
        - name: Checkout Source
          uses: actions/checkout@v3
        - name: setup java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
        - name: Build Project
          run: mvn clean install -DskipTests
        - name: Upload Artifact for Deploymnet job
          uses: actions/upload-artifact@v3
          with:
              name: SpringB-NoDB-App
              path: ${{github.workspace}}/target/*.jar
   deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
          - name: Download artifact from build job
            uses: actions/download-artifact@v3
            with:
              name: SpringB-NoDB-App
          - name: deploy to azure app service
            uses: azure/webapps-deploy@v3
            with:
              app-name: SpringB-NoDB-App
              publish-profile: ${{secrets.azureWebAppPublishProfile}}
              package: '*.jar'